name: Trigger Webhook on Push and PR

on:
  push:
    branches:
      - '**'
  pull_request:
    types: [opened, closed, synchronize]

jobs:
  send-webhook:
    runs-on: ubuntu-latest
    steps:
      - name: Setup the env vals
        env:
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
        run: echo "Webhook URL is set."

      - name: Send webhook to Flask server
        run: |
          if [ "${{ github.event_name }}" == "push" ]; then
            action="push"
            author="${{ github.actor }}"
            ref="${{ github.ref }}"
            timestamp="${{ github.event.head_commit.timestamp }}"
          elif [ "${{ github.event_name }}" == "pull_request" ]; then
            action="${{ github.event.action }}"
            author="${{ github.actor }}"
            ref="${{ github.event.pull_request.head.ref }}"
            timestamp="${{ github.event.pull_request.updated_at }}"
          fi

          curl -X POST -H "Content-Type: application/json" \
          -d '{"action": "'"$action"'", "author": "'"$author"'", "ref": "'"$ref"'", "timestamp": "'"$timestamp"'"}' \
          $WEBHOOK_URL
